apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: k8s-testserver
    namespace: default
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: k8s-testserver
    template:
      metadata:
        labels:
          app: k8s-testserver
      spec:
        containers:
        - image: epflsti/k8s-testserver
          imagePullPolicy: Always
          name: k8s-testserver
          ports:
          - containerPort: 3000
            protocol: TCP
